[package]
name = "tide-compress"
version = "0.4.0"
authors = ["Jeremiah Senkpiel <fishrock123@rocketmail.com>"]
edition = "2018"
license = "BlueOak-1.0.0"
description = "Outgoing compression middleware for the Tide web framework."
readme = "README.md"
repository = "https://github.com/Fishrock123/tide-compress"
keywords = ["tide", "middleware", "gzip", "compression"]
categories = [
  "web-programming::http-server"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["brotli", "gzip"]
all = ["brotli", "gzip", "deflate"]

brotli = ["async-compression/brotli"]
gzip = ["async-compression/gzip"]
deflate = ["async-compression/deflate"]

[dependencies]
async-compression = { version = "0.3", features = ["futures-bufread"] }
futures-util = { version = "0.3", features = ["io"] }
regex = "1.3"
tide = "0.13"

[dev-dependencies]
async-h1 = "2.1"
async-std = { version = "1.6", features = ["attributes"] }
