[package]
name = "tide-compress"
version = "0.1.0"
authors = ["Jeremiah Senkpiel <fishrock123@rocketmail.com>"]
edition = "2018"
license = "BlueOak-1.0.0"
description = "Outgoing compression middleware for the Tide web framework."
readme = "README.md"
repository = "https://github.com/Fishrock123/tide-compress"
keywords = ["tide", "middleware", "gzip", "compression"]
categories = [
  "web-programming::http-server"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["brotli", "gzip"]
all = ["brotli", "gzip", "deflate"]

brotli = ["async-compression/brotli"]
gzip = ["async-compression/gzip"]
deflate = ["async-compression/deflate"]

[dependencies]
async-compression = { version = "0.3", features = ["futures-bufread"] }
async-std = { version = "1.5", features = ["unstable"] }
futures = "0.3"
http-types = { git = "https://github.com/http-rs/http-types.git", branch = "master" }
tide = { git = "https://github.com/jbr/tide.git", branch = "update-http-types" }

[dev-dependencies]
async-h1 = { git = "https://github.com/jbr/async-h1.git", branch = "update-http-types" }
async-std = { version = "1.5", features = ["unstable", "attributes"] }
