[package]
name = "tide-compress"
version = "0.1.0"
authors = ["Jeremiah Senkpiel <fishrock123@rocketmail.com>"]
edition = "2018"
license = "BlueOak-1.0.0"
description = "Outgoing compression middleware for the Tide web framework."
readme = "README.md"
repository = "https://github.com/Fishrock123/tide-compress"
keywords = ["tide", "middleware", "gzip", "compression"]
categories = [
  "web-programming::http-server"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-compression = { version = "0.3", features = ["futures-bufread", "gzip"] }
async-std = { version = "1.4.0", features = ["unstable"] }
futures = "0.3"
http-types = "1.0"
tide = { git = "https://github.com/Fishrock123/tide.git", branch = "response-remove-header" }

[dev-dependencies]
async-std = { version = "1.4.0", features = ["unstable", "attributes"] }
surf = "2.0.0-alpha.1"
