[package]
name = "tide-compress"
version = "0.1.0"
authors = ["Jeremiah Senkpiel <fishrock123@rocketmail.com>"]
edition = "2018"
license = "BlueOak-1.0.0"
description = "Outgoing compression middleware for the Tide web framework."
readme = "README.md"
repository = "https://github.com/Fishrock123/tide-compress"
keywords = ["tide", "middleware", "gzip", "compression"]
categories = [
  "web-programming::http-server"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["brotli", "gzip"]
all = ["brotli", "gzip", "deflate"]

brotli = ["async-compression/brotli"]
gzip = ["async-compression/gzip"]
deflate = ["async-compression/deflate"]

[dependencies]
async-compression = { version = "0.3", features = ["futures-bufread"] }
async-std = { version = "1.5", features = ["unstable"] }
futures = "0.3"
http-types = "1.2"
tide = { git = "https://github.com/Fishrock123/tide.git", branch = "request-response-impl-asref-and-into" }

[dev-dependencies]
async-h1 = "1.1.2"
async-std = { version = "1.5", features = ["unstable", "attributes"] }
surf = "2.0.0-alpha.1"
